### ISSUE TITLE
Is this repo still usable?

### ISSUE THREAD

**Issue by erikkaplun** [SWI-Prolog/swipl-wasm#11]
The rla/swipl-devel repo is significantly behind the SWI-prolog/swipl-devel repo, but the latter lacks the wasm branch.

**Comment by JanWielemaker** [comment]
WASM support is provided by the master branch.  Build instructions are in `CMAKE.md` in the top directory.   There has also been some discussion about experiences on the [Discourse](https://swi-prolog.discourse.group/) forum recently.
