### ISSUE TITLE
How to set user input in the "console"

### ISSUE THREAD

**Issue by ArneVogel** [SWI-Prolog/swipl-wasm#8]
I am trying to figure out how to interact with prolog. How could I set what a user inputs in the "interactive shell" (no idea if thats the correct wording here)? How could give the system inputs after submitting a query: https://i.imgur.com/zqoxrwB.png
Currently I instantly get `ERROR: char_code/2: Type error: `character_code' expected, found `-1' (an integer)` after submitting my query. How would I let the system know I want more solutions `;`?

I am getting the same behavior on the demo site: http://demos.rlaanemets.com/swi-prolog-wasm/example/

---
I looked further into it and I think I would have to use [PL_open_query](https://www.swi-prolog.org/pldoc/man?section=foreign-create-query)? But I have problems understanding the arguments. Are there any more examples that explain that?

**Comment by rla** [comment]
There are no examples with PL_open_query in the SWI wasm project. There is only example with PL_call: https://github.com/SWI-Prolog/swipl-wasm/blob/master/example/index.html#L138

You would need to dig into examples of using SWI-Prolog FLI and then adjust them to the Emscripten JS/WASM binding layer.
